# This workflow run unit tests for the SDK as well as a build. It will then
# run npm publish if the preceding steps succeeded.

name: Linode Cloud Manager

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install:all
    - name: Build
      run: yarn build
    - name: Unit tests
      run: yarn test
