# This workflow run unit tests for the SDK as well as a build. It will then
# run npm publish if the preceding steps succeeded.

# container:
#     image: cypress/browsers:node12.18.0-chrome83-ff77

name: Linode Cloud Manager - E2E

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: yarn install:all && yarn run cypress verify && yarn build:sdk && touch ./packages/manager/.env
    - name: E2E Cypress
      run: sh ./run_cypress_docker.sh
      env:
        MANAGER_OAUTH: ${{ secrets.MANAGER_OAUTH }}
        REACT_APP_LAUNCH_DARKLY_ID: ${{ secrets.REACT_APP_LAUNCH_DARKLY_ID }}
        REACT_APP_LOGIN_ROOT: https://login.linode.com
        REACT_APP_API_ROOT: https://api.linode.com/v4
        MANAGER_USER: ${{ secrets.MANAGER_USER }}
