# This workflow run unit tests for the SDK as well as a build. It will then
# run npm publish if the preceding steps succeeded.

name: Linode Cloud Manager - E2E

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
    - name: Install
      run: yarn install:all && yarn build:sdk
    - name: E2E Cypress
      uses: cypress-io/github-action@v2
      with:
        build: yarn build:sdk && touch ./packages/manager/.env
        start: yarn workspace linode-manager start
        wait-on: http://localhost:3000
        project: ./packages/manager
      env:
        MANAGER_OAUTH: ${{ secrets.MANAGER_OAUTH }}
        REACT_APP_LAUNCH_DARKLY_ID: ${{ secrets.REACT_APP_LAUNCH_DARKLY_ID }}