# This workflow run unit tests for the SDK as well as a build. It will then
# run npm publish if the preceding steps succeeded.

name: Linode Cloud Manager - E2E

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: E2E Cypress
      uses: cypress-io/github-action@v2
      with:
        build: yarn install:all && yarn build:sdk && touch ./packages/manager/.env
        start: yarn workspace linode-manager start
        wait-on: http://localhost:3000
        command: yarn cy:e2e
      env:
        MANAGER_OAUTH: ${{ secrets.MANAGER_OAUTH }}
        REACT_APP_LAUNCH_DARKLY_ID: ${{ secrets.REACT_APP_LAUNCH_DARKLY_ID }}